CREATE SEQUENCE SEQ_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USUARIOS (
                              USUARIO_ID INTEGER DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL,
                              NOME VARCHAR2(100) NOT NULL,
                              EMAIL VARCHAR(100) UNIQUE NOT NULL,
                              SENHA VARCHAR(100) NOT NULL,
                              ROLE VARCHAR(20) DEFAULT 'USER' NOT NULL
);

CREATE SEQUENCE SEQ_EMAIL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_EMAIL (
                           EMAIL_ID INTEGER DEFAULT SEQ_EMAIL.NEXTVAL NOT NULL,
                           REMETENTE VARCHAR2(256) NOT NULL,
                           DESTINATARIO VARCHAR(256) NOT NULL,
                           ASSUNTO VARCHAR(256) NOT NULL,
                           MENSAGEM VARCHAR(1000) NOT NULL,
                           DATA_ENVIO TIMESTAMP NOT NULL
);

CREATE SEQUENCE SEQ_EVENTO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_EVENTO (
                            EVENTO_ID INTEGER DEFAULT SEQ_EVENTO.NEXTVAL NOT NULL,
                            NOME VARCHAR2(100) NOT NULL,
                            DESCRICAO VARCHAR(1000) NOT NULL,
                            DATA TIMESTAMP NOT NULL
);

ALTER TABLE TBL_EMAIL ADD CONSTRAINT FK_EMAIL_REMETENTE FOREIGN KEY (REMETENTE) REFERENCES TBL_USUARIOS(EMAIL);
ALTER TABLE TBL_EMAIL ADD CONSTRAINT FK_EMAIL_DESTINATARIO FOREIGN KEY (DESTINATARIO) REFERENCES TBL_USUARIOS(EMAIL);